### ISSUE TITLE
Can I use tabular  multi instance?

### ISSUE THREAD

**Issue by SenerDemiral** [aldeed/meteor-tabular#166]

**Comment by sgaluza** [comment]
Yes, you can use multiple instances on the same template without any problems.
For example if you define:

```javascript
TabularTables.Instance1 = new Tabular.Table({...})
TabularTables.Instance2 = new Tabular.Table({...})
```
You can then use them on template:
```javascript
{{> tabular table=TabularTables.Instance1}}
{{> tabular table=TabularTables.Instance2}}
```
In some cases you need to use the same collection in both instances and it will work fine. However you can't use the same instance on the same template, because the tables will use the same collection subscription.

**Comment by SenerDemiral** [comment]
Thank you. 
I tried to use "multiple instance of the template".
Is there a easy way to clone Tabular.Table structure? (without copy&paste)

**Comment by sgaluza** [comment]
Not sure if it helps, but you can try something like: https://lodash.com/docs#cloneDeep

**Comment by SenerDemiral** [comment]
Thanks anyway.

**Comment by jdnichollsc** [comment]
Hi guys
@aldeed  Any example to create dynamic instances with the same template?

Thanks in advance, Nicholls
