### ISSUE TITLE
Feature request: Show/hide columns

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-tabular#204]
I really like the package but it would be really great if it was possible to show/hide columns in the table dynamically.

**Comment by aldeed** [comment]
It should work the same as with normal DataTables. Did you try? http://datatables.net/examples/api/show_hide.html

**Comment by thearabbit** [comment]
Please example, how to use it in this?

**Comment by timstew** [comment]
Here is a very basic example of a template event that I've wired up to a button with an id of #btn_toggle that toggles visibility of the first column. The id of the table was just obtained from inspecting the HTML of the generated table, however I just realized that you can set the table id from the markup like such:

```
{{> tabular id="table_id" ... }} 
```

This was adapted and simplified from link above aldeed gave, because my use case was very simple.

```javascript
    'click #btn_toggle':function(e,t){
        var table = $('#table_id').DataTable();
        var column = table.column(0);
        column.visible( ! column.visible() );
    }
```

**Comment by ericwikman** [comment]
in the DataTables docs it shows that you can also hide columns by definition by setting visible to false. This doesn't seem to work with tabular but other definitions work fine (like searchable). I tried with both columns and columnDefs.

**Comment by aldeed** [comment]
`visible` works fine. I use it often.

**Comment by luixal** [comment]
@aldeed is it posible to use a function to set the `visible` value in table definition?

I've tried some approaches with no luck.
