### ISSUE TITLE
Selector callback isn't firing when using Blaze.renderWithData

### ISSUE THREAD

**Issue by AdamBrodzinski** [aldeed/meteor-tabular#216]
I'm trying to render the tables with Blaze's `renderWithData` and i'm having trouble getting the `selector` key to fire with a function. It works if I hard code an object but when I pass a func. it never fires. Is there something obvious that i'm missing?

The main reason i'm doing this is to use render the table in React. However I may have to fallback to creating a Blaze template for each table and passing that in instead.

    var templateOpts = {
      table: new Tabular.Table(tableOpts),
      class: classNames,

      // works!
      selector: { name: "Oranges" }

      // doesn't work, never fires :(
      selector: function() {
        console.log("Test");
        return { name: "Oranges" };
      }
    };

    Blaze.renderWithData(
      Template.tabular,
      templateOpts,
      rootDiv
    );

**Comment by AdamBrodzinski** [comment]
Also I can confirm that creating a wrapper Blaze template that passes it in the normal way and then using `Blaze.render` renders that wrapper template. Perhaps `renderWithData` doesn't take a function the same way?

**Comment by aldeed** [comment]
This seems like a peculiarity of renderWithData. It probably doesn't resolve the functions the same way it would in template context. So this is the equivalent of having `selector=selector` and then having your `selector` helper return a function that returns the selector, rather than the selector itself. It would not make sense to change tabular for this. You might have to call renderWithData in an autorun if you need to simulate reactive functions.

**Comment by AdamBrodzinski** [comment]
Yep you're right on the money. Sorry I forgot to close this. I ended up forking and adding a bit of code to call the function when passing in a function. I agree, def. not something to merge into Tabular though.
