### ISSUE TITLE
Feature Request: Enable Spinner-Support for waiting

### ISSUE THREAD

**Issue by thebarty** [aldeed/meteor-tabular#227]
Hi @aldeed,

*(getting my head around Flow-Router...)* 
I just stumbled upon **``Template.subscriptionsReady``.**

**Tabular should have an option to show a spinner while data is loading.** Maybe with the option to specify a spinner-template-name as a parameter.
I think it would be really easy to implement within the ``tabular.html``` file with the help of the above function.

**I think this should do it already:**
```
    <!-- client/table.html -->
    {{#if Template.subscriptionsReady}}
        <table {{atts}}></table>
    {{else}}
        {{>spinner}}
    {{/if}}    
```

This is the place to find more info:
https://www.discovermeteor.com/blog/template-level-subscriptions/

**Comment by aldeed** [comment]
I'm trying to make everything go through the datatables API, which in this case is the "processing" state. There is code already that tries to do this properly, but it obviously isn't working. I will look at it again when I have time.

**Comment by maxko87** [comment]
@thebarty, I tried that fix in a fork and it didn't work for me. I'm also super interested in a solution to this -- did you come up with an intermediate one that worked?

**Comment by thebarty** [comment]
Hey max,

no I don't have a solution for this. 

My "solution" is a comment in the code reminding me to wait for a solution ﻿:-)

```
    {{! todo: Wait for aldeed:tabular to support a spinner}}
    {{! see request https://github.com/aldeed/meteor-tabular/issues/227 }}
```

**Comment by gb96** [comment]
I have spinner mostly working, the only problem is I cannot handle the edge-case where no data is returned and an empty table is rendered, in which case spinner never disappears.

My _interim_ solution outlined below: 
* Spinner is provided via the `sacha:spin` package, and rendered in page template depending on a Session var "talkingToServer" (and a Template helper function named "talkingToServer"):
```html
    {{! MyTemplate.html }}
    {{#if talkingToServer}}
    {{> spinner}}
    {{/if}}
```
```javascript
// /client/_Helpers.js
Template.registerHelper(
    "talkingToServer",
    function () {
        return Session.get("talkingToServer"); // flag to display spinner while loading data
    }
);
```
* Spinner is enabled as soon as the page containing the DataTable is rendered:
```javascript
// /client/MyTemplate.js
Template.MyTemplate.rendered = function () {
  Session.set("talkingToServer", true); // flag to display spinner while loading
  // ...
};
```
* One Tabular.Table column definition must define a render function, and the render function disables the spinner:
```javascript
// /both/tabular/tabularTables.js
TabularTables.Customers= new Tabular.Table({
    name: "CustomerList",
    collection: db.customer,
    columns: [
        {
            data: "name",
            title: "Customer Name",
            render: function (val, type, doc) {
                Session.set("talkingToServer", false); // flag to hide spinner after first data has loaded
                return val;
            }
        }
    ],
    initComplete: function (settings, json) {
        // note this method never seems to be called!
        // doc: https://datatables.net/reference/option/initComplete 
        Session.set("talkingToServer", false); // flag to hide spinner after first data has loaded
    }
});
```

This works quite well, main problem is when the server does not return any data (typically because search/filter criteria are too specific) and the spinner never stops.  I'm thinking of either using a setTimeout() method to turn the spinner off after say 30 seconds, alternatively going with the Iron Router loading template approach (described in http://www.meteor-tutorial.org/book/1_3_first_app_part_3#uid307 )

**Comment by aldeed** [comment]
Indicator fixed in https://github.com/aldeed/meteor-tabular/commit/8e7b14d33354f745169cde0161369329772395c7
