### ISSUE TITLE
Option to choose the type of search behavior ($and or $or) in the default search field

### ISSUE THREAD

**Issue by lucasfurlani** [aldeed/meteor-tabular#239]
Hi there,

With the update to 1.4.0 (https://github.com/aldeed/meteor-tabular/releases/tag/v1.4.0) the behavior of the search field changed ("When entering multiple search terms, the search now splits them by whitespace and uses OR matching").

That said, what is the best way to change it back to the old behavior (not splitting by whitespaces - https://github.com/aldeed/meteor-tabular/blob/aaf34c45d7e1f29ebf71613f162c4efa41466d0e/client/pubSelector.js#L40)?

Currently the best way I found to solve this is to create another search field and change the search params in the selector.

In case there isn't, would it be viable to have an option like "{splitSearchByWhitespaces: true}"? And if yes, which is the best way to implement this feature (for a pull request)?

**Comment by aldeed** [comment]
Added this option in https://github.com/aldeed/meteor-tabular/commit/1eeb82c13f9d962ff3503e52c5a30975336656b5

**Comment by drtomasso** [comment]
Is it possible to use smart search with an $and matcher? Would be usefull searching in multiple columns with $and. Using it in my old PHP project with custom server-side script, has been very usefull with the $and matcher in multi column search.

**Comment by aldeed** [comment]
@drtomasso I'm not sure I understand. Can you give an example?

**Comment by drtomasso** [comment]
Example log table:

Date | Level | Message
------ | ------- | ---------
2016-01-01 | warning | something happened
2016-01-02 | info | just some info

Searching for all warnings in 2016, typing: `2016 warning`
With smart filter on, it will split the search term, search all columns using $or. The result is both lines, since both lines have `2016` OR `warning` in one of their fields.
With smart filter off, it will search for `2016 warning` in a single column, meaning it will not return any result.

**Comment by aldeed** [comment]
OK, so it would split and do $or within a single document property, but all terms would have to be present somewhere in the same document. I understand. @drtomasso Can you submit this as a new issue with your example in it?
