### ISSUE TITLE
updateRecords Error : can't wait without a fiber

### ISSUE THREAD

**Issue by prdox29** [aldeed/meteor-tabular#278]
i get a recurrent error which crash my app and cause meteor to restart.
What can i do to resolve this ?

The error comes from aldeed_tabular/server/tabular.js:118:1 :

throw new Error('Can\'t wait without a fiber');
W20160222-21:46:42.046(1)? (STDERR)     at Function.wait (C:\Users\Seb\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:155:9)
W20160222-21:46:42.046(1)? (STDERR)                   ^
W20160222-21:46:42.048(1)? (STDERR)     at Timer.listOnTimeout [as ontimeout](timers.js:121:15)
W20160222-21:46:42.043(1)? (STDERR)
W20160222-21:46:42.047(1)? (STDERR)     at updateRecords (packages/aldeed_tabular/server/tabular.js:118:1)

Thank you for your help

**Comment by prdox29** [comment]
The same Error :

W20160223-21:23:49.180(1)? (STDERR)             throw new Error('Can\'t wait without a fiber');
W20160223-21:23:49.180(1)? (STDERR)                   ^
W20160223-21:23:49.180(1)? (STDERR) Error: Can't wait without a fiber
W20160223-21:23:49.180(1)? (STDERR)     at Function.wait (C:\Users\Seb\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:155:9)
W20160223-21:23:49.180(1)? (STDERR)     at Object.Future.wait (C:\Users\Seb\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:397:10)
W20160223-21:23:49.180(1)? (STDERR)     at [object Object]._.extend.count (packages/mongo/mongo_driver.js:1059:1)
W20160223-21:23:49.180(1)? (STDERR)     at [object Object].Cursor.(anonymous function) [as count] (packages/mongo/mongo_driver.js:869:1)
W20160223-21:23:49.180(1)? (STDERR)     at updateRecords (packages/aldeed_tabular/server/tabular.js:118:1)
W20160223-21:23:49.180(1)? (STDERR)     at [object Object].later [as _onTimeout] (packages/underscore/underscore.js:695:1)
W20160223-21:23:49.185(1)? (STDERR)     at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

**Comment by bpartridge** [comment]
This seems to occur because, when you add or remove a record that matches the selection, updateRecord is called, but because this happens within observeChanges (which doesn't seem to set up a fiber), it's trying to call countCursor.count() synchronously without a fiber, which is impossible given that network activity to Mongo is taking place! This combination of lines seems to fix it, but I haven't tested it fully, nor do I 100% understand everything that is going on - I'd like to do so before submitting a PR. Anyone encountering this issue in the meantime is welcome to use my https://github.com/belstone/meteor-tabular/tree/count-fibers branch.

**Comment by bpartridge** [comment]
Incidentally, this was repeatedly crashing our app when we upgraded today to latest tabular, since background processes (writing directly into Mongo and observed via the oplog) will often reclassify rows out of a user's table while it is open (thereby triggering observeChanges)! So it will get reasonably tested over the next few days.

**Comment by JuliaKoe** [comment]
@bpartridge : How do I implement your package?

**Comment by aldeed** [comment]
@bpartridge I'd like to better understand the root cause of this. The code in question works fine for me and I assume most people. Do you know what situations cause there to be no fiber when it runs? What version of Meteor? If we can add a test where it breaks, it will be easier to figure out the proper fix. Recreating the cursor every time will be slower, so I'd like to avoid it if there's another way to fix or a different root cause.

**Comment by JuliaKoe** [comment]
I have meteor 1.2.1. Meteor crashes when data is updated in the underlying mongo collection. I used this package to display data straight from the collection. I have a background process that updates the data (calculations), and at that time it crashed on the dev. machine and on the server (AWS) likewise.

**Comment by JuliaKoe** [comment]
I also might add that I was subscribing on a Template level.

**Comment by bpartridge** [comment]
@aldeed Also want to understand the root cause, I agree that recreating the cursor isn't optimal!

@JuliaKoe We also have a background process writing to Mongo, and the error happens when it makes a change that would move a row in or out of the table.

I'm thinking out loud here, but perhaps if the single Meteor instance is the only thing making changes to the collection (which is how most people use Meteor), then Meteor is running all the observeChanges within a fiber already... but if the change is coming from *oplog tailing,* then observeChanges might just be triggered from a node callback, not an actual fiber? Or perhaps the count is cached if all the changes are being made through Meteor, and that cache is invalidated if oplog entries come in?

In the meantime @JuliaKoe if you need a quick fix, you can simply clone and checkout the branch I linked into `your_app_directory_where_meteor_is_running/packages/aldeed_tabular`. Then Meteor on restart should use the local copy rather than fetching the Atmosphere-published mainline version. It's a good idea to use git submodules for this, and make sure your server deploy runs the necessary submodule checkout commands. Plenty of articles on google about cloning local packages as submodules.

**Comment by diegoconcha** [comment]
@aldeed, @JuliaKoe, @bpartridge so good and bad news. I created a package to incorporate @bpartridge fix but it didn't work for us. Instead we simply removed the "throttleRefresh" option when creating a new table with tabular and it fixed the problem. We were setting it to 5 sec. Times longer than that caused the error. 1 sec didn't cause the error but for now we're just going to remove it all together.

**Comment by bpartridge** [comment]
I think I've (finally) tracked it down - I was just bandaging the problem with my earlier fix rather than fixing it!

The core of the problem is that .count() is called synchronously, and regardless of when/where countCursor was created, this call needs to be in a Fiber if Meteor had any reason to believe that Mongo changed separately from its own actions (i.e. another server or external process wrote to the database).

Meteor.setTimeout, which I introduced in my earlier fix, created a Fiber and fixed some of the problems... but it was doing so *around the _.throttle*. And _.throttle(func) can sometimes call func synchronously, but sometimes asynchronously if it actually hits the throttle condition. So in situations where the count was dirty, *and* throttling was triggered, then the Fiber would never wrap the actual thing that we needed a Fiber to wrap!

So the *actual* fix should be a lot simpler than my branch: just wrap updateRecords in Meteor.bindEnvironment *before* it gets throttle-wrapped. I'm doing some final testing and will make a PR shortly.

**Comment by aldeed** [comment]
Wrapped it in bindEnvironment. Thanks
