### ISSUE TITLE
Stuck on Processing

### ISSUE THREAD

**Issue by baberuth22** [aldeed/meteor-tabular#321]
About 1 in 5 times when I click on a column header to sort, the sort doesn't actually happen and the "processing" indicator text doesn't go away.

I have to sort again to make the message disappear.

Please advise me toward a solution.

**Comment by luixal** [comment]
Happens to me too. Really annoying as users are just waiting for the message to disappear...

**Comment by baberuth22** [comment]
Can this get some attention?  It's incredibly important that this doesn't happen or it renders this package unusable.

**Comment by redcap3000** [comment]
I think it may be highly related to queries that return nothing as a page first loads. If you can ensure that the first query that uses data tables has a result set that is a very unusable workaround.

**Comment by ffigueroa** [comment]
Same issue when i click on pages... :(

**Comment by luixal** [comment]
@redcap3000 it happens on both cases, when first page has no data and when you have plenty of pages full of data.

It also happens when loading the whole template or just on page changing.

It seems pretty random to me :8ball:

**Comment by ghybs** [comment]
Hi,

Could it be related to #252?
If so, would PR #318 solve this situation as well?

**Comment by baberuth22** [comment]
It sounds like PR #318  could fix my problem.  How would I pull this into my Meteor project without the package being updated?

**Comment by ghybs** [comment]
I think `meteor add aldeed:tabular@https://github.com/gaiazov/meteor-tabular.git#20c5c335621c2e98f3158aca8ae6360ca163b5f7` should work.

However, PR #318 was built using `devel` branch, which is 5 commits behind `master` branch, and 5 commits ahead…
Furthermore, as mentioned on issue #327, it seems that version 1.6.1 was pushed on Atmosphere (hence that is the version you automatically get from the standard `meteor add aldeed:tabular`), but the GitHub repo (`master` branch) is still at 1.5.5… whereas `devel` branch is indeed at 1.6.1. So it is confusing which version is published?

At least you could give it a try.
Please let us know if your problem is fixed by that PR.

**Comment by aldeed** [comment]
Should be fixed in 2.0
