### ISSUE TITLE
Non-orderable first column appears orderable at first

### ISSUE THREAD

**Issue by aldeed** [aldeed/meteor-tabular#48]
When using default initial sorting, the first column appears orderable at first. Once you click to sort another column, the first column's arrow goes away.

This might be a DataTables bug. Need to investigate further.

**Comment by jfols** [comment]
This is because the default behavior of DT is to order the first column https://github.com/DataTables/DataTables/issues/339.
DT applies the sort class regardless of if the column is sortable, thus why the class goes away once you click sort on another column.
You can can fix by settings no order on the table `order: []` or by setting an initial column to order on `order: [[2, 'desc']]`.
