### ISSUE TITLE
v1.0.4 => processing.dt fires weird

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-tabular#52]
Here is a reproduction for the closed issue: https://github.com/aldeed/meteor-tabular/issues/44

Using tabular v0.2.3 ```$(window).on('processing.dt')``` fires as it should (when we click next page). It fires once for **processing=true** then after some time (ex. 525.444ms) once again for **processing=false**. This is natural desired behaviour.

**Console output for each next-page click using v0.2.3** => http://tabular-v0-2-3.meteor.com
```
Tue Jan 20 2015 12:08:42 GMT+0100 (CET) processing.dt=true
Tue Jan 20 2015 12:08:42 GMT+0100 (CET) processing.dt=false
processing.dt=true: 525.444ms
```
Using tabular v1.0.4 ```$(window).on('processing.dt')``` fires **four times** for each next-page click. First it fires **true** and **false** very quickly (ex. 7.543ms) and when processing finishes it fires **true** and **false** again. Thats why my loading spinner was not showing and I originally thought that the event was not firing at all, but after deeper inspection it seems it is firing too much in a weird way.

**Console output for each next-page click using v1.0.4** => http://tabular-v1-0-4.meteor.com/
```
Tue Jan 20 2015 12:13:26 GMT+0100 (CET) processing.dt=true
Tue Jan 20 2015 12:13:26 GMT+0100 (CET) processing.dt=false
processing.dt=true: 7.543ms
Tue Jan 20 2015 12:13:27 GMT+0100 (CET) processing.dt=true
Tue Jan 20 2015 12:13:27 GMT+0100 (CET) processing.dt=false
processing.dt=true: 7.510ms
```

And here is my code: https://github.com/boustanihani/tabular-processing

**Comment by aldeed** [comment]
This is to be expected. The ajax function is currently called twice for every action. I'm so far not able to think of any other solution that still retains all the additional reactivity added in 1.0, but I'm sure there is probably some way to do it that I haven't thought of yet.

**Comment by boustanihani** [comment]
I'm trying to understand your internal implementation, maybe I come up with some idea for fixing this :)

Just wan't to make sure, is it because of this line getting called twice: ```table.ajax.reload(null, false);```
https://github.com/aldeed/meteor-tabular/blob/v1.0.4/client/tabular.js#L288

Could you shortly describe why it must be called twice?

**Comment by aldeed** [comment]
It's difficult to shortly describe.

1. We need sort, skip, limit, search, etc. values, which DataTables gives us whenever it calls the `ajax` function.
2. At that point we need to subscribe to the data page that results from those values. So we update reactive variables, which causes subscription 1 and then subscription 2 to be stopped and rerun.
3. While we're waiting for this to happen, we go ahead and call the `callback` that DataTables provided us.
4. When the doc subscription is ready, we call `reload` so that the `ajax` function will run again. This time we update the reactive variables again, but they have not changed so nothing reacts. This second run is simply so that we can call the provided callback again, this time with the correct `data`.

That's actually the simple part. In order to make the list also react to outside changes to the doc set, to selector changes, etc., we have additional autoruns that can also cause the subscriptions to rerun. So there are definitely better ways to do the steps outlined above, but the trick is to do them and still retain the ability to trigger reloads and subscription reruns based on other things, but without spiraling into an infinite loop of reactivity.

**Comment by aldeed** [comment]
Processing message is shown fairly accurately in the latest release. It probably still doesn't fire the event in a logical way, but that can't be fixed. If someone needs this, we could fire our own event for load start and stop.
