### ISSUE TITLE
Comparison with ephemer:reactive-datatables

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-tabular#62]
Thanks for adding a comparison with the @LumaPictures package at the top of the README. The other significant prior art would be @ephemer's [reactive-datatables](https://atmospherejs.com/ephemer/reactive-datatables). What would be the main differences from that package?

**Comment by lc3t35** [comment]
Today 428 installed for ephemer's package (Last commit March 18th, 4 iterations since 1.0.0)
![capture d ecran 2015-04-25 a 18 14 43](https://cloud.githubusercontent.com/assets/921372/7333645/922ea4d8-eb77-11e4-87cc-784e3110a675.png)
1342 for aldeed (Last commit April 23th,  8 iterations since 1.0.0)
![capture d ecran 2015-04-25 a 18 14 24](https://cloud.githubusercontent.com/assets/921372/7333650/a76f113e-eb77-11e4-85e1-7e09e52749aa.png)

**Comment by aldeed** [comment]
Ha, the wisdom of crowds. :)

Actually there are probably more substantive differences, but I've never had a chance to dig into @ephemer's package. I know that at the time I created this, I couldn't get good dynamic subscription performance for large datasets with any of the existing packages. Otherwise I would have used one of those because I'm lazy.

**Comment by ephemer** [comment]
My package has about 100 lines of code including templates and is a lightweight wrapper for providing datatable reactivity for a reactive dataset that's essentially already on the client. (I don't manage subscriptions or anything like that). 

It starts to die at about 5000 data points in our main use case. Until then it's fine and probably the best option (in terms of small codebase and UI speed) unless you really need the other features. For more features or larger datasets I'd almost certainly use aldeed's package

**Comment by aldeed** [comment]
Thanks, @ephemer. I'd agree with that. It would be cool to think about some way to have two separate packages, one lightweight one that does the basics, and then the option to plug in the additional package to get the subscription management for large datasets. Realistically it'll be a long time until I have time to explore that, but it could be cool.

**Comment by ephemer** [comment]
@dandv does that answer your original question?
