### ISSUE TITLE
Selector reactivity causing pagination problems

### ISSUE THREAD

**Issue by dkoo761** [aldeed/meteor-tabular#71]
OK, this is one of the stranger bugs I've found :)

It only occurs in the following situation:

1) Provide a selector property that contains a reactive variable such as Meteor.user()
2) In the Tabular.Table definition, set `collection: Meteor.users`
3) Add a column in the Tabular.Table definition that is not normally published in the Meteor.users collection (ie. a column other than _id, emails or profile).

In this case, the table displays fine, but if I paginate to the 2nd page of results, I see the 2nd page for a split second and then I am returned to the first page again.

My current workaround is to disable reactivity in the selector:

``` javascript
selector: function () {
    return Tracker.nonreactive(function () {
        return { 'profile.orgId': Meteor.user().profile.orgId }
    });
}
```

**Comment by dkoo761** [comment]
I just moved my selectors from client-side to server-side and that had the side-effect of fixing this issue in my case. So this is only still an issue for people using client-side selectors.

**Comment by aldeed** [comment]
Right. Reactive selectors on the client is one of the goals, so we'll have to fix this eventually.

**Comment by arleonard** [comment]
Very similar issue here with the following circumstances:
1) Using a session variable as a selector
2) Using a custom publishComposite function.
Oddly enough, it is only a problem when I use a selector in the child. So
```
find: (shipment) ->
 Shipment_Document.find({shipment_id: shipment._id}, {fields: {type: 1, shipment_id: 1}})
```
does not work but
```
find: (shipment) ->
 Shipment_Document.find({}, {fields: {type: 1, shipment_id: 1}})
```
does work.

**Comment by steve-ross** [comment]
FWIW I only see this issue with publish composite...

**Comment by steve-ross** [comment]
@defionscode Can we bump the version and publish this?

**Comment by MohammedEssehemy** [comment]
@aldeed @defionscode  could you check here and bump the version to atmosphere?

**Comment by ZeEarth** [comment]
Hello everybody, 

I have the same problem on the last version. I use a ReactivVar in an helper to change the selector. 
When my ReactivVar content an array with a single value it's okay, but since I put an extra value, pagination doesn't work anymore, selector is fine. 

`selectorEmployees() {
    const filterSelector = Template.instance().filter.get().map((x) => {
      return parseInt(x, 10);
    });
    console.log(filterSelector);
    return { idEmployee: { $in: filterSelector } };
  },`

Should I open a new case for this ?

**Comment by MohammedEssehemy** [comment]
@ZeEarth 
the fix is merged in the master branch but not published yet on atmosphere.
so you should download the repo to your packages folder in the root of your working directory and then remove tabular and add it again.

**Comment by ZeEarth** [comment]
@MohammedEssehemy 
Same after downloading master branch, remove the package and add the package again. 
Works like a charm with one value in the array and KO since a second value added in the ReactiveVar.

**Comment by jorisroling** [comment]
I've found that using the sector function reactive, it is runs (because of Tracker.autorun) too often and prevents going to the next page. By being careful with assigning to those ReactiveVars only when actually changed (see below) this is prevented.

I use this code (both server & client):
```
import { ReactiveVar } from 'meteor/reactive-var'
import equal from 'fast-deep-equal'

ReactiveVar.prototype.setIfChanged = function(val) {
  if (!equal(val,this.get())) {
    return this.set(val)
  }
}
```
and then use <ReactiveVar>.setIfChanged(value) to make the selector only be called (autoran) when actual new values arrive.

Hope it helps!
