### ISSUE TITLE
Feature Request: DT plug-ins and extensions

### ISSUE THREAD

**Issue by kirilan** [aldeed/meteor-tabular#73]
It will be really useful if the next versions include the filtering and file export plugins and extensions:

http://www.datatables.net/extensions/tabletools/

http://www.datatables.net/plug-ins/filtering/

**Comment by aldeed** [comment]
Most plugins should work without changes needed in this package. Filtering won't because this package uses `serverSide` option and the filtering plugin docs state that the plugin has no effect when doing server side processing.

If there are certain filtering features you want, you could suggest those specifically and we may or may not be able to add support for it.

**Comment by kirilan** [comment]
what would be the proper folder to place the extensions ? sorry for the rookie question but I am still somewhat lost with this

**Comment by aldeed** [comment]
Probably /client/lib

**Comment by kirilan** [comment]
it uses some sort of flash magic for the the csv/excel export stuff I cant get to work I think I'll just give up. Thanks bunch for trying to help anyway.
