### ISSUE TITLE
table Template instance isn't reactive

### ISSUE THREAD

**Issue by ajlin500** [aldeed/meteor-tabular#85]
I have an application which dynamically uses different TabularTables based on a session variable. When the session variable changes, the table data changes from the reactive selector but the number of columns and titles remain the same.

**Comment by aldeed** [comment]
I designed it to be reactive, but I don't recall ever actually testing that scenario, so I'll have to look into it.

**Comment by ajlin500** [comment]
Awesome. Thanks! Really epic package overall man

**Comment by dovrosenberg** [comment]
I believe the issue is that in line 103 of tabular.js, you're checking the table name.  If the table name hasn't changed, it never makes it to the rest of the checks, so options doesn't get updated, so the other autorun never runs.

    if (tabularTable.name === lastTableName) 
        if (table) {
         ...
       }
       return;
    }

I'd try to fix it, but it's not immediately clear to me what the desired behavior is.  Should a name change be required to change columns (for example)?  Or are there a subset of tabular fields that should be updated regardless of a name change?

**Comment by almogdesign** [comment]
I'm also running into this issue when I change the user language the table does not load new lang. I tried using autorun

**Comment by aldeed** [comment]
Trying to catch up. Can you check if this is still an issue with the 1.3.0 release? Be sure you have `aldeed:tabular@1.3.0` explicitly in your packages file or package `use`, or it may actually load an older release.

**Comment by dovrosenberg** [comment]
From what I can tell, 1.3.0 appears to have resolved this.  Thanks!
