### ISSUE TITLE
Quite long initialization

### ISSUE THREAD

**Issue by kk4sh** [aldeed/meteor-tabular#96]
My initial publication (tabular_get info) is quite long ( about 1.5sec). 
I just want to know if it is a normal behavior.
It seems two passes are done and one of them without filtering with the limited number of docs
Here is the trace from kadira: 

![image](https://cloud.githubusercontent.com/assets/9833071/6494181/2da6a478-c2c0-11e4-9f1d-92384b0d2b16.png)

**Comment by aldeed** [comment]
Thanks for pointing this out @kk4sh. There are two observes, correct, but the second one, the ["count" observe](https://github.com/aldeed/meteor-tabular/blob/master/server/tabular.js#L116), I think should have options passed `{fields: {_id: 1}, sort: {_id: 1}}` in order to optimize the observe because we care only about doc count.

If you can try this change and do a pull request, I'll accept it. Otherwise I should hopefully have some time to get through tabular issues in the next week.

**Comment by jasonxeno** [comment]
Does the 'sort: {_id: 1}' need to be there if it is only getting the count? I would think it would be faster without any sorting but maybe there is a reason for it being there?

**Comment by aldeed** [comment]
I was thinking that sort is needed to optimize oplog, but I was misremembering. It is needed only when `limit` is provided (see [here](https://kadira.io/academy/optimize-your-app-for-oplog/)), but in this case we are not limiting, so you are correct, we don't need sort.

**Comment by aldeed** [comment]
Should be fixed in 1.5.0
